name: Docker Image CD

on:
  workflow_run:
    workflows: ['Docker Image CI']
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted
   
    steps:
    
    - name: Pull Docker Image
      run: sudo docker pull satyamshikhar/flask-ci-cd

    - name: Delete old container
      run: sudo rm -rf ci-cd-pipeline-container || true

    - name: Run Docker Container
      run: sudo docker run -dp 5000:5000 --name ci-cd-pipeline-container satyamshikhar/flask-ci-cd
      
    
